### ISSUE TITLE
Preserve owner using CI_JOB_TOKEN

### ISSUE THREAD

**Issue by ahmet2mir** [go-semantic-release/provider-gitlab#3]
Hello,

It will be very useful to use CI_JOB_TOKEN for [CreateRelease](https://github.com/go-semantic-release/provider-gitlab/blob/master/pkg/provider/gitlab.go#L168) func only (all others needs API access).

Currently we generate a [PAT](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) but the pipeline running the release is owned by the PAT account  not by the person who run the "parent" pipeline.

Any chance to allow both ? or at lease show the payload  (so I could curl it using ci_job_token) ?

**Comment by cliedeman** [comment]
@ahmet2mir Sorry I missed this issue. 

I didn't think about using it only for release. I'll revisit this depending on how using only how the other implementation fairs because I think it's the cleaner solution

**Comment by ahmet2mir** [comment]
Hello all, 

No problem I close this issue in favor of the new one. 

For future, is it better to create the issue on the provider part (no response in 10 months) or directly on semantic release repo (got response in few days) ?
